import Head from 'next/head'
import styles from '../styles/Home.module.css'
import app from '../lib/firebase'
import { DocumentData, getFirestore, QuerySnapshot } from "firebase/firestore";
import { collection, addDoc, getDocs } from "firebase/firestore"; 
import { useEffect, useState } from 'react';
import { TikTokScraper } from '../api/TikTok/src';



const db = getFirestore(app)



export default function Home() {
  const [docs, setDocs] = useState<QuerySnapshot<DocumentData> | null>(null)
  const scraper = new TikTokScraper();

  async function getTrends() {
    return scraper.getTrending()
  }

  async function getTrendsAPI() {
    const response = await fetch('/api/trending')
    const value = await response.json()
    console.log(value);

  }

  async function testing() {
    try {
      const docRef = await addDoc(collection(db, "users"), {
        first: "Ada",
        last: "Lovelace",
        born: 1815
      });
      console.log("Document written with ID: ", docRef.id);
      updateState()
    } catch (e) {
      console.error("Error adding document: ", e);
    }
  }

  const updateState = async () => {
    const querySnapshot = await getDocs(collection(db, "users"));
    querySnapshot.forEach((doc) => {
      console.log(`${doc.id} => ${doc.data()}`);
    });
    setDocs(querySnapshot)
  }

  useEffect(() => {
    updateState()
  }, [])
  
  console.log(docs)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <button className='bg-slate-900' onClick={testing}>add user</button>
    <button className='bg-green-900' onClick={getTrends}>Get Trends</button>
    <button className='bg-red-900' onClick={getTrendsAPI}>Get Trends</button>

    <p className='text-lg'>test</p>
    </div>
  )
}



