import Head from 'next/head'


// type in a profile and get some data about it.
// --avg times posted / day over past 30 days
// --growth over past 30 days

export default function Tool() {




  

  return (
    <div className='text-center' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <h1 className="text-4xl m-5">Peitho</h1>

  
    </div>
  )
}



